export const STORE_QUESTION_RESULTS = 'STORE_QUESTION_RESULTS';
export const CHANGE_QUESTION_INDEX = 'CHANGE_QUESTION_INDEX';
export const GET_RESULTS = 'GET_RESULTS';
export const GET_RESULTS_SUCCESS = 'GET_RESULTS_SUCCESS';
export const GET_RESULTS_FAILED = 'GET_RESULTS_FAILED';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const LOG_IN_FAILED = 'LOG_IN_FAILED';
export const LOG_OUT = 'LOG_OUT';